CREATE TABLE IF NOT EXISTS livros (
    id_livro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    ano_publicacao INTEGER NOT NULL CHECK (ano_publicacao BETWEEN 0 AND EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER),
    quantidade INTEGER NOT NULL DEFAULT 1 CHECK (quantidade >= 0),
    id_autor INTEGER NOT NULL,
    id_categoria INTEGER NOT NULL,
    CONSTRAINT fk_livros_autor
        FOREIGN KEY (id_autor)
        REFERENCES autores(id_autor)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_livros_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categorias(id_categoria)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);
