CREATE TABLE IF NOT EXISTS emprestimos (
    id_emprestimo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_livro INTEGER NOT NULL,
    id_leitor INTEGER NOT NULL,
    data_emprestimo DATE NOT NULL DEFAULT CURRENT_DATE,
    data_prevista DATE NOT NULL,
    data_devolucao DATE,
    CONSTRAINT ck_emprestimo_datas
        CHECK (data_prevista >= data_emprestimo),
    CONSTRAINT ck_devolucao_data
        CHECK (data_devolucao IS NULL OR data_devolucao >= data_emprestimo),
    CONSTRAINT fk_emprestimos_livro
        FOREIGN KEY (id_livro)
        REFERENCES livros(id_livro)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_emprestimos_leitor
        FOREIGN KEY (id_leitor)
        REFERENCES leitores(id_leitor)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);
