-- Gamificação: catálogo de conquistas que um leitor pode desbloquear.
CREATE TABLE IF NOT EXISTS conquistas (
    id_conquista INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    pontos_bonus INTEGER NOT NULL DEFAULT 0 CHECK (pontos_bonus >= 0)
);
