-- Gamificação: níveis do leitor, calculados por faixa de pontuação acumulada.
-- O nível NÃO é armazenado no leitor (evita dado duplicado/desatualizado);
-- ele é sempre calculado comparando o total de pontos com pontos_minimos.
CREATE TABLE IF NOT EXISTS niveis (
    id_nivel INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL UNIQUE,
    pontos_minimos INTEGER NOT NULL UNIQUE CHECK (pontos_minimos >= 0)
);
