-- Gamificação: histórico que explica a origem de cada ponto do leitor.
-- id_emprestimo é opcional (pontos de bônus de conquista não vêm de um empréstimo específico).
CREATE TABLE IF NOT EXISTS historico_pontos (
    id_historico INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_leitor INTEGER NOT NULL,
    id_emprestimo INTEGER,
    pontos INTEGER NOT NULL,
    motivo VARCHAR(120) NOT NULL,
    data_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_historico_pontos_nao_zero CHECK (pontos <> 0),
    CONSTRAINT fk_historico_leitor
        FOREIGN KEY (id_leitor)
        REFERENCES leitores(id_leitor)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_historico_emprestimo
        FOREIGN KEY (id_emprestimo)
        REFERENCES emprestimos(id_emprestimo)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);
